### PR TITLE
change strong to b

### PR DESCRIPTION
**Pull request by whaus7**

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @whaus7 , `strong` is also a valid tag for bold text. Any specific reason for preferring `b`.

**Comment by whaus7** [comment]
Hey jPuri! Stupid bbedit for php supposedly doesn't like <strong> im not a
backend guy so I didn't feel like messing around with the bbedit side

**Comment by jpuri** [comment]
Ah I see, I would prefer to make this configurable to select tag for a style. I would be open to a PR for this. Or I will make this change myself as I get time.
Thanks for bringing up this requirement.

**Comment by whaus7** [comment]
Awesome! I was going to do a PR for that and then delete these packages I
published. I was just forking and publishing for 2 reason. 1. Ive never
published a package before on NPM and wanted to learn. And 2. Just needed a
quick fix. Wasn't sure how responsive you would be. When I get some time
this week ill try to make a PR for the config settings. But please dont be
too harsh! I'm just starting to get into the open source scene. Been a
consuming mole rat for the longest time

**Pull request closed without merging**
